function display_axis(axes_object, origin, base_axes, quiverscale, varargin)
%DISPLAY_AXIS Summary of this function goes here
%   Detailed explanation goes heredefault_tag = "plot";

default_tag = "plot";

p = inputParser;
addRequired(p, 'axes_object');
addRequired(p, 'origin');
addRequired(p, 'base_axes');
addRequired(p, 'quiverscale');
addParameter(p, 'Tag', default_tag, @isstring);

parse(p, axes_object, origin, base_axes, quiverscale, varargin{:});

quiver3( axes_object, ...
         origin(1), ...
         origin(2), ...
         origin(3), ...
         base_axes(1,1) * quiverscale, ...
         base_axes(2,1) * quiverscale, ...
         base_axes(3,1) * quiverscale, ...
         'LineWidth', 2, 'Color', 'r', ...
         'Tag', p.Results.Tag);
quiver3( axes_object, ...
         origin(1), ...
         origin(2), ...
         origin(3), ...
         base_axes(1,2) * quiverscale, ...
         base_axes(2,2) * quiverscale, ...
         base_axes(3,2) * quiverscale, ...
         'LineWidth', 2, 'Color', 'g', ...
         'Tag', p.Results.Tag);
quiver3( axes_object, ...
         origin(1), ...
         origin(2), ...
         origin(3), ...
         base_axes(1,3) * quiverscale, ...
         base_axes(2,3) * quiverscale, ...
         base_axes(3,3) * quiverscale, ...
         'LineWidth', 2, 'Color', 'b', ...
         'Tag', p.Results.Tag);
     
end

